services:
  video-call-db:
    image: postgres:16-alpine
    container_name: video-call-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_call_db
    ports:
      - "15432:5432"
    volumes:
      - video-call-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  video-call-db-data:
